[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asyncio_utils"
version = "0.1.0"
description = "Timers and Rate Limiters"
requires-python = ">=3.12"
